# Generated by Django 2.1 on 2019-08-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=120)),
                ('isbn', models.IntegerField()),
                ('publisher_name', models.CharField(max_length=120)),
                ('publisher_date', models.DateField()),
                ('category', models.CharField(max_length=120)),
                ('stocks', models.IntegerField()),
            ],
        ),
    ]
